name: CD_MEGAFILE

on:
  push:
    branches:
      - "main"

jobs:
  builder:
    name:
      Build apk
    runs-on: 
      [ubuntu-latest]
    defaults:
      run:
        working-directory: 
          ./cinescope
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Flutter 
        uses: subosito/flutter-action
        with: 
          channel: stable
          flutter: cinescope/pubspec.yaml
          flutter-version: 3.13.7
          cache: true

      - name: Make final apk
        uses: actions/upload-artifact@v4
        with:
          name:
            final-apk-build
          path:
            cinescope/build/app/outputs/apk/release
            

  deployer:
      name:
        Deply apk
      runs-on: 
        [ubuntu-latest]
      defaults:
        run:
          working-directory: 
            ./cinescope
      steps:
        - name: Clone repository
          uses: actions/checkout@v4

        - name: Setup Flutter 
          uses: subosito/flutter-action
          with: 
            channel: stable
            flutter: cinescope/pubspec.yaml
            flutter-version: 3.13.7
            cache: true


        - name: Deploy apk
          uses: actions/download-artifact@v4
          with:
            name: final-apk-build


            